modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
[[mods]]
modId="scythe"
version="${file.jarVersion}"
displayName="Scythe Mod"
logoFile="scythe.png"
credits="Yes"
authors="Torchwood_one and 1JamesLeDolphin"
description='''
This mod adds a very called weapon known as the Scythe. I hope you enjoy it.
'''
[[dependencies.scythe]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
